### ISSUE TITLE
Actively enforce commit message style

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/pipeline#27]
There are a number of options for enforcing our styleguide as defined in `CONTRIBUTING.md`.

- https://gitcop.com/home for webhook-based validation
  - **Note**: does not support local validation
- git hooks, for example: https://gist.github.com/jasonrobertfox/8057124

TODOs:

- [x] Set up GitCop for Pipeline
- [x] Test out GitCop on a PR

**Comment by bvtsang** [comment]
Just to clarify, by local validation do you mean enforcing the commit message style before pushing to Github? Or did you mean something else?

**Comment by 0xazure** [comment]
Correct.  Local validation is enforcing the commit message style _before_ changed get pushed publicly.

**Comment by bvtsang** [comment]
As far as I can tell, of the existing options:

## Gitcop

### Pros

- Easy message style enforcement for _all_ contributors

### Cons

- Does not support local validation
  - But commit messages can be reviewed in pull requests and fixed post-push with force pushing

## git hooks

### Pros

- Message style enforcement before commits get pushed

### Cons

- Requires contributors to set up git hooks

**Comment by blackjackkent** [comment]
Is there a reason we can't do both? Githooks for local validation and then gitcop to run if the branch makes it to the PR stage?

**Comment by bvtsang** [comment]
We could do both! It'll be on the (future) contributors to install the git hooks though.

**Comment by blackjackkent** [comment]
That would be the case anyway, though. (And we could potentially gist them and use the setup script to download them if it became necessary later on.)

**Comment by 0xazure** [comment]
Okay, so I _think_ I've gotten GitCop set up properly, we'll just have to wait to test it out on a PR.

Thoughts on kicking local validation down the road?  Or should we get that set up at the same time?

**Comment by blackjackkent** [comment]
I'm okay with kicking local validation for now. we can each set up our own local hooks as needed.

**Comment by bvtsang** [comment]
Gitcop tested on a pull request: https://github.com/new-xkit/pipeline/pull/22#issuecomment-154612664

**Comment by 0xazure** [comment]
GitCop's rules may need tweaking in the future, but it looks like this is done for now.
